# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.1

steps:
  #################
  # Gradle Wrapper Validation
  #################
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: *common_plugins

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  #################
  # Instrumented (aka UI) Tests
  #################
  - group: "🔬 Instrumented tests"
    steps:
      - label: ":wordpress: 🔬 Instrumented tests"
        command:
        - ".buildkite/commands/instrumented-tests.sh wordpress"
        - "ls -la **/build/instrumented-tests/**/*"
        - "cat **/build/instrumented-tests/**/test_result_1.xml"
        plugins: *common_plugins
        artifact_paths:
          - "**/build/instrumented-tests/**/*"
